[package]
name = "ros2_data_extraction"
version = "0.1.0"
edition = "2024"

[dependencies]
# Асинхронный стек
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time", "sync"] }
futures = "0.3.34"

ros2-client = { version = "0.10.1", default-features = false, features = ["humble"] }
rustdds = "0.14.2"
rerun = "0.37.2"

# Логирование и воркспейс
shared.workspace = true
tracing = "0.1.44"
