[workspace]
members = [
    "cuda-pipeline",
    "rust_listener",
    "data-extraction",
    "shared",
    "jitter_test"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
cuda-pipeline = { path = "cuda-pipeline" }
ros2_data_extraction = { path = "data-extraction" }
kaiv_utils = { git = "https://github.com/kaiv-dev/kaiv_utils.git", rev = "fdaf82e", features = ["env_config_macro", "trace_err"] }
shared = {path = "shared"}