services:
  # 1. Сервис плеера — остаётся на ROS2
  # АСТМАТИК 👎
  # ros2_dataset_player:
  #   build:
  #     context: .
  #     dockerfile: ./dataset/Dockerfile
  #   container_name: ros2_dataset_player
  #   network_mode: "host"
  #   ipc: "host"
  #   shm_size: '2gb'
  #   ulimits:
  #     nofile:
  #       soft: 1024
  #       hard: 65535
  #   environment:
  #     - ROS_DOMAIN_ID=42
  #     - ROS_LOCALHOST_ONLY=1
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./dataset:/app/dataset:ro
  #   command: >
  #     bash -c "
  #       echo '► [DATASET] Поехали!' &&
  #       ros2 bag play /app/dataset/roundT_doubleT --loop --read-ahead-queue-size 50
  #     "
  ros2_fast_player:
    build:
      context: .
      dockerfile: ./bag_player/Dockerfile
    container_name: ros2_fast_player
    network_mode: "host"
    ipc: "host"
    environment:
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=1
    env_file:
      - .env
    volumes:
      - ./dataset:/app/dataset:ro
    command: ["/app/dataset/roundT_pressureGate_roundT"]
    
  # 2. Rust-приложение — без ROS2, чистый ros2-client/rustdds
  rust_viewer:
    build:
      context: .
      dockerfile: ./rust_listener/Dockerfile
    container_name: rust_viewer
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ipc: "host"
    shm_size: '2gb'
    env_file:
      - .env # ⚠️⚠️⚠️ ДОКЕР У МЕНЯ ПОЧЕМУ - ТО ДОСТУЧАТЬСЯ ТОЛЬКО ПО СЕТИ РОУТЕРА
    cap_add:
      - NET_ADMIN
    volumes:
      - ./frames:/frames
    ulimits:
      nofile:
        soft: 1024
        hard: 65535
    environment:
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=1
    depends_on:
      - ros2_fast_player
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
