[package]
name = "rust_listener"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ros2_debug_viewer"
path = "src/main.rs"

[dependencies]
r2r = { git = "https://github.com/sequenceplanner/r2r", branch = "master" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
futures = "0.3"
anyhow = "1"
rerun = "0.37.2"
test_lib.workspace = true
