[package]
name = "rust_listener"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ros2_debug_viewer"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1"
rerun = "0.37.2"

cuda-pipeline = { workspace = true }
ros2_data_extraction = { workspace = true }
ddl = { workspace = true }