[package]
name = "rust_listener"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ros2_debug_viewer"
path = "src/main.rs"

[[bin]]
name = "rail_detector"
path = "src/bin/rail_detector.rs"

[[bin]]
name = "rail_tuner"
path = "src/bin/rail_tuner.rs"

[[bin]]
name = "rail_tuner_2d"
path = "src/bin/rail_tuner_2d.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1"
rerun = "0.37.2"
eframe = "0.36.2"
egui = "0.36.2"
image = { version = "0.25", default-features = false, features = ["png"] }
rusqlite = { version = "0.32", features = ["bundled"] }
cdr = "0.2"
byteorder = "1.5"

cuda-pipeline.workspace = true
ros2_data_extraction.workspace = true
shared.workspace = true
kaiv_utils.workspace = true
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ros2-interfaces-jazzy-serde = { version = "0.0.5", features = ["sensor_msgs"] }
rayon = "1.12.0"
tracing-appender = "0.2.5"
