[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2.0.20"
anyhow = "1.0.104"
ros2-client = { version = "0.10.1", default-features = false, features = ["humble"] }
serde = { version = "1.0.229", features = ["derive"] }
rerun = "0.37.2"
tracing = "0.1.44"
rayon = "1.12.0"

